In [3]:
name = "Aidan"
print(f"Hello { name }")


Hello Aidan


In [5]:
import numpy as np

r = np.random.randint(1, 10, (5, 5))

print (r)

# for row in r:
#     for column in row:
#         print (column)

print(r[2][2])



[[9 8 7 3 5]
 [4 3 1 7 7]
 [7 1 3 2 6]
 [2 3 4 9 2]
 [3 6 4 7 5]]
3


In [8]:
values = np.random.randint(1, 10, (1, 20))

print (values)

print (values[0][0])




[[6 1 5 7 8 9 6 2 2 6 4 1 4 4 9 2 9 5 3 2]]
6


In [11]:
data = np.random.randint(1, 10, (5, 5))

column = data[0:4, 1]

print (data)
#print (column)

for column_index in range(len(data[0])):  # length of any row is the num of columns
    column = data[:, column_index]
    print(f"column {column_index + 1}, {column}")




[[6 3 1 1 9]
 [3 3 8 4 2]
 [3 4 1 8 1]
 [2 3 2 8 5]
 [5 8 8 1 7]]
column 1, [6 3 3 2 5]
column 2, [3 3 4 3 8]
column 3, [1 8 1 2 8]
column 4, [1 4 8 8 1]
column 5, [9 2 1 5 7]


In [14]:
rnumbers = np.random.randint(1, 10, (1, 9))

print (rnumbers)

square = np.reshape(rnumbers, (3, 3))

print(square)

print (type(square))

[[8 8 3 9 1 6 6 8 3]]
[[8 8 3]
 [9 1 6]
 [6 8 3]]
<class 'numpy.ndarray'>
